AWSTemplateFormatVersion: "2010-09-09"
Description: >
  ETL Lambda / Step Functions バッチ監視用 CloudWatch アラーム一式
  - ジョブ別 成功率 SLO（3ジョブ）
  - バッチ全体（Step Functions）失敗検知
  - バッチ全体 処理時間 P95 SLO
  - 上記を束ねるコンポジットアラーム（通知はここに集約）

Parameters:
  Namespace:
    Type: String
    Default: "ETL/Batch"
    Description: "CloudWatch メトリクスの Namespace（デフォルト: ETL/Batch）"

  JobCategory:
    Type: String
    Default: "critical"
    Description: "JobCategory ディメンション値（現状は critical 固定運用を想定）"

  ExecutionEnv:
    Type: String
    Default: "lambda"
    Description: "ExecutionEnv ディメンション値（Lambda 版: lambda / 将来の AWS Batch 版: awsbatch 等）"

  SnsTopicArn:
    Type: String
    Description: "コンポジットアラーム通知先 SNS トピックの ARN を指定してください"

  StateMachineArn:
    Type: String
    Description: "Step Functions ステートマシン（バッチ全体）の ARN を指定してください"

  JobSuccessRateThreshold:
    Type: Number
    Default: 99.5
    Description: "ジョブ成功率 SLO（%）。デフォルト 99.5%。"

  BatchDurationP95ThresholdSeconds:
    Type: Number
    Default: 600
    Description: "バッチ全体処理時間 P95 の SLO（秒）。デフォルト 600 秒 = 10 分。"

Resources:

  # ------------------------------------------------------------
  # 1. ジョブ別 成功率 SLO アラーム（3 ジョブ）
  #    - EMF の JobSucceeded / JobFailed を使って成功率を算出
  #    - 期間: 300 秒（5 分）、直近 1 データポイントを評価
  #    - TreatMissingData: notBreaching（データなし = 正常）
  #    - SNS 通知は付けず、「子アラーム」として扱う
  # ------------------------------------------------------------

  SasakiEtlLambdaOrderSummarySuccessRateSloAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: "sasaki-etl-lambda-order-summary-success-rate-slo"
      AlarmDescription: >
        【ジョブ監視】ETL Lambda ジョブ order_summary の成功率 SLO アラーム。
        直近 5 分間の成功率がしきい値を下回った場合に ALARM 状態になります。
        SLO: 成功率 >= JobSuccessRateThreshold（デフォルト 99.5%）。

      ComparisonOperator: LessThanThreshold
      Threshold: !Ref JobSuccessRateThreshold
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      TreatMissingData: notBreaching
      ActionsEnabled: false

      Metrics:
        # 成功数
        - Id: m1_success
          MetricStat:
            Metric:
              Namespace: !Ref Namespace
              MetricName: JobSucceeded
              Dimensions:
                - Name: JobType
                  Value: order_summary
                - Name: JobCategory
                  Value: !Ref JobCategory
                - Name: ExecutionEnv
                  Value: !Ref ExecutionEnv
            Period: 300
            Stat: Sum
          ReturnData: false

        # 失敗数
        - Id: m2_failure
          MetricStat:
            Metric:
              Namespace: !Ref Namespace
              MetricName: JobFailed
              Dimensions:
                - Name: JobType
                  Value: order_summary
                - Name: JobCategory
                  Value: !Ref JobCategory
                - Name: ExecutionEnv
                  Value: !Ref ExecutionEnv
            Period: 300
            Stat: Sum
          ReturnData: false

        # 成功率 (%)
        - Id: success_rate
          Label: "OrderSummary Job Success Rate (%)"
          Expression: "IF((FILL(m1_success,0) + FILL(m2_failure,0)) == 0, 100, 100 * FILL(m1_success,0) / (FILL(m1_success,0) + FILL(m2_failure,0)))"
          ReturnData: true

  SasakiEtlLambdaInventoryUpdateSuccessRateSloAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: "sasaki-etl-lambda-inventory-update-success-rate-slo"
      AlarmDescription: >
        【ジョブ監視】ETL Lambda ジョブ inventory_update の成功率 SLO アラーム。
        直近 5 分間の成功率がしきい値を下回った場合に ALARM 状態になります。
        SLO: 成功率 >= JobSuccessRateThreshold（デフォルト 99.5%）。

      ComparisonOperator: LessThanThreshold
      Threshold: !Ref JobSuccessRateThreshold
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      TreatMissingData: notBreaching
      ActionsEnabled: false

      Metrics:
        - Id: m1_success
          MetricStat:
            Metric:
              Namespace: !Ref Namespace
              MetricName: JobSucceeded
              Dimensions:
                - Name: JobType
                  Value: inventory_update
                - Name: JobCategory
                  Value: !Ref JobCategory
                - Name: ExecutionEnv
                  Value: !Ref ExecutionEnv
            Period: 300
            Stat: Sum
          ReturnData: false

        - Id: m2_failure
          MetricStat:
            Metric:
              Namespace: !Ref Namespace
              MetricName: JobFailed
              Dimensions:
                - Name: JobType
                  Value: inventory_update
                - Name: JobCategory
                  Value: !Ref JobCategory
                - Name: ExecutionEnv
                  Value: !Ref ExecutionEnv
            Period: 300
            Stat: Sum
          ReturnData: false

        - Id: success_rate
          Label: "InventoryUpdate Job Success Rate (%)"
          Expression: "IF((FILL(m1_success,0) + FILL(m2_failure,0)) == 0, 100, 100 * FILL(m1_success,0) / (FILL(m1_success,0) + FILL(m2_failure,0)))"
          ReturnData: true

  SasakiEtlLambdaReportGenerationSuccessRateSloAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: "sasaki-etl-lambda-report-generation-success-rate-slo"
      AlarmDescription: >
        【ジョブ監視】ETL Lambda ジョブ report_generation の成功率 SLO アラーム。
        直近 5 分間の成功率がしきい値を下回った場合に ALARM 状態になります。
        SLO: 成功率 >= JobSuccessRateThreshold（デフォルト 99.5%）。

      ComparisonOperator: LessThanThreshold
      Threshold: !Ref JobSuccessRateThreshold
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      TreatMissingData: notBreaching
      ActionsEnabled: false

      Metrics:
        - Id: m1_success
          MetricStat:
            Metric:
              Namespace: !Ref Namespace
              MetricName: JobSucceeded
              Dimensions:
                - Name: JobType
                  Value: report_generation
                - Name: JobCategory
                  Value: !Ref JobCategory
                - Name: ExecutionEnv
                  Value: !Ref ExecutionEnv
            Period: 300
            Stat: Sum
          ReturnData: false

        - Id: m2_failure
          MetricStat:
            Metric:
              Namespace: !Ref Namespace
              MetricName: JobFailed
              Dimensions:
                - Name: JobType
                  Value: report_generation
                - Name: JobCategory
                  Value: !Ref JobCategory
                - Name: ExecutionEnv
                  Value: !Ref ExecutionEnv
            Period: 300
            Stat: Sum
          ReturnData: false

        - Id: success_rate
          Label: "ReportGeneration Job Success Rate (%)"
          Expression: "IF((FILL(m1_success,0) + FILL(m2_failure,0)) == 0, 100, 100 * FILL(m1_success,0) / (FILL(m1_success,0) + FILL(m2_failure,0)))"
          ReturnData: true

  # ------------------------------------------------------------
  # 2. バッチ全体（Step Functions）用 子アラーム
  #    2-1. 実行失敗検知（ExecutionsFailed > 0）
  #    2-2. 処理時間 P95 SLO（ExecutionTime p95 > しきい値）
  #    ※ここでも SNS は付けず、コンポジットの材料としてのみ利用
  # ------------------------------------------------------------

  SasakiEtlBatchExecutionFailedAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: "sasaki-etl-batch-execution-failed"
      AlarmDescription: >
        【バッチ監視】Step Functions ステートマシンの ExecutionsFailed > 0
        を検知するアラーム。1 回でも失敗が記録された場合に ALARM になります。

      ComparisonOperator: GreaterThanThreshold
      Threshold: 0
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      TreatMissingData: notBreaching
      ActionsEnabled: false

      Metrics:
        - Id: sf_failed
          MetricStat:
            Metric:
              Namespace: "AWS/States"
              MetricName: "ExecutionsFailed"
              Dimensions:
                - Name: StateMachineArn
                  Value: !Ref StateMachineArn
            Period: 300
            Stat: Sum
          ReturnData: true

  SasakiEtlBatchDurationP95SloAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: "sasaki-etl-batch-duration-p95-slo"
      AlarmDescription: >
        【バッチ監視】Step Functions ステートマシンの ExecutionTime P95 が
        しきい値（デフォルト 600 秒 = 10 分）を超えた場合に ALARM になる子アラーム。
        SLO: バッチ全体処理時間 P95 <= BatchDurationP95ThresholdSeconds。

      ComparisonOperator: GreaterThanThreshold
      Threshold: !Ref BatchDurationP95ThresholdSeconds
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      TreatMissingData: notBreaching
      ActionsEnabled: false

      Metrics:
        - Id: sf_duration_p95
          MetricStat:
            Metric:
              Namespace: "AWS/States"
              MetricName: "ExecutionTime"
              Dimensions:
                - Name: StateMachineArn
                  Value: !Ref StateMachineArn
            Period: 300
            Stat: p95
          ReturnData: true

  # ------------------------------------------------------------
  # 3. コンポジットアラーム（通知集約用）
  #    - 通知させたい条件だけを OR で束ねる
  #    - SNS はこのコンポジットにのみ付与
  # ------------------------------------------------------------

  SasakiEtlLambdaBatchCriticalCompositeAlarm:
    Type: AWS::CloudWatch::CompositeAlarm
    Properties:
      AlarmName: "sasaki-etl-lambda-batch-critical-composite"
      AlarmDescription: >
        【重要通知】ETL バッチ全体に重大な問題が発生したことを通知する
        コンポジットアラーム。
        条件:
          - Step Functions バッチ実行失敗
          - いずれかのジョブで成功率 SLO 違反
          - バッチ全体処理時間 P95 の SLO 違反
        実際の SNS 通知はこのアラームにのみ設定し、子アラームには SNS を付けません。

      AlarmRule: !Sub >
        ALARM('${SasakiEtlBatchExecutionFailedAlarm}')
        OR ALARM('${SasakiEtlLambdaOrderSummarySuccessRateSloAlarm}')
        OR ALARM('${SasakiEtlLambdaInventoryUpdateSuccessRateSloAlarm}')
        OR ALARM('${SasakiEtlLambdaReportGenerationSuccessRateSloAlarm}')
        OR ALARM('${SasakiEtlBatchDurationP95SloAlarm}')

      ActionsEnabled: true
      AlarmActions:
        - !Ref SnsTopicArn